### ISSUE TITLE
Smart Search functionality - prioritize as short-term improvement?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#1]
https://www.w3.org/WAI/EO/wiki/WAI_site_plans has:

> The highest priority for the IA of the site is to have really good search ability

Is there any reason to wait to do that? I'd like for us to consider making that a short-term improvement that we start very soon.

**Comment by yatil** [comment]
Aspects
- [ ] Explore what is needed to implement such a functionality.
- [ ] Setting meta tags to resources
- [ ] Defining meta tags needed
- [ ] Prioritize items
- [ ] What should be displayed first
- [ ] What are the options and how will we do it?
- [ ] Defining the technical backend
- [ ] Defining the user interface
- [ ] Defining the details

**Comment by yatil** [comment]
Split into #6, #7, #8, #9
